#!/bin/bash

#POSSIBLE SOLUTION TO THE SALON APPOINMENT SCHEDULER PROJECT

PSQL="psql -X --username=freecodecamp --dbname=salon --tuples-only -c"

echo -e "\n~~~~~ MY BARBERSHOOP ~~~~~"
echo -e "\nWelcome to my barbershop, how can I help you?\n" 

MAIN_MENU() {

  SERVICES=$($PSQL "SELECT service_id, name FROM services")
  echo "$SERVICES" | while read SERVICE_ID BAR NAME
  do
    echo "$SERVICE_ID) $NAME"
  done

  echo -e "\nWhat service would you like?"
  read SERVICE_ID_SELECTED

  # Get the name of the selected service
  SELECTED_SERVICE_NAME=$($PSQL "SELECT name FROM services WHERE service_id=$SERVICE_ID_SELECTED")


  case $SERVICE_ID_SELECTED in
  1) HAIRCUT "$SELECTED_SERVICE_NAME" "$SERVICE_ID_SELECTED";;
  2) SHAVE "$SELECTED_SERVICE_NAME" "$SERVICE_ID_SELECTED";;
  3) BEARD_TRIM "$SELECTED_SERVICE_NAME" "$SERVICE_ID_SELECTED";;
  *) MAIN_MENU "I could not find that service. What would you like today?";;
  esac
}

HAIRCUT() {
  SERVICE_NAME=$1
  SERVICE_ID=$2

  echo -e "\nWhat's your phone number?"
  read CUSTOMER_PHONE

  CUSTOMER_PHONE_NUMBER=$($PSQL "SELECT phone FROM customers WHERE phone='$CUSTOMER_PHONE'")

  if [[ -z $CUSTOMER_PHONE_NUMBER ]]
  then
    echo "I don't have a record for that phone number, what's your name?"
    read CUSTOMER_NAME
    echo "What time would you like your $SERVICE_NAME, $CUSTOMER_NAME?"
    read SERVICE_TIME
    echo "I have put you down for a $SERVICE_NAME at $SERVICE_TIME, $CUSTOMER_NAME."
  else 
    echo "What time would you like your $SERVICE_NAME, $CUSTOMER_NAME?"
    read SERVICE_TIME
    echo "I have put you down for a $SERVICE_NAME at $SERVICE_TIME, $CUSTOMER_NAME."

  fi
  
  INSERT_CUSTOMER=$($PSQL "INSERT INTO customers(phone, name) VALUES('$CUSTOMER_PHONE', '$CUSTOMER_NAME')")

  #GET CUSTOMER_D
  CUSTOMER_ID=$($PSQL "SELECT customer_id FROM customers")
  
  #INSERT APPOINTMENT INTO DATABASE
  INSERT_APPOINTMNET=$($PSQL "INSERT INTO appointments(time, customer_id, service_id) VALUES('$SERVICE_TIME', $CUSTOMER_ID, '$SERVICE_ID')")
}

SHAVE() {
  SERVICE_NAME=$1
  SERVICE_ID=$2

  echo -e "\nWhat's your phone number?"
  read CUSTOMER_PHONE

  CUSTOMER_PHONE_NUMBER=$($PSQL "SELECT phone FROM customers WHERE phone='$CUSTOMER_PHONE'")

  if [[ -z $CUSTOMER_PHONE_NUMBER ]]
  then
    echo "I don't have a record for that phone number, what's your name?"
    read CUSTOMER_NAME
    echo "What time would you like your $SERVICE_NAME, $CUSTOMER_NAME?"
    read SERVICE_TIME
    echo "I have put you down for a $SERVICE_NAME at $SERVICE_TIME, $CUSTOMER_NAME."
  fi

  INSERT_CUSTOMER=$($PSQL "INSERT INTO customers(phone, name) VALUES('$CUSTOMER_PHONE', '$CUSTOMER_NAME')")
}

BEARD_TRIM() {
  SERVICE_NAME=$1
  SERVICE_ID=$2 

  echo -e "\nWhat's your phone number?"
  read CUSTOMER_PHONE

  CUSTOMER_PHONE_NUMBER=$($PSQL "SELECT phone FROM customers WHERE phone='$CUSTOMER_PHONE'")

  if [[ -z $CUSTOMER_PHONE_NUMBER ]]
  then
    echo "I don't have a record for that phone number, what's your name?"
    read CUSTOMER_NAME
    echo "What time would you like your $SERVICE_NAME, $CUSTOMER_NAME?"
    read SERVICE_TIME
    echo "I have put you down for a $SERVICE_NAME at $SERVICE_TIME, $CUSTOMER_NAME."
  fi

  INSERT_CUSTOMER=$($PSQL "INSERT INTO customers(phone, name) VALUES('$CUSTOMER_PHONE', '$CUSTOMER_NAME')")
}

MAIN_MENU
